theme: jekyll-theme-leap-day
title: Marco Pellin
facebook: https://www.facebook.com/marco.pellin.94
linkedin: http://it.linkedin.com/pub/marco-pellin/81/205/937/
youtube: https://www.youtube.com/user/marco87italy
show_social: true
